version: '3.9'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: horilla
      POSTGRES_USER: horillauser
      POSTGRES_PASSWORD: horillapassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://horillauser:horillapassword@db:5432/horilla

volumes:
  postgres_data:
